/**
 * Cielo24
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: devs@cielo24.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export type IWPEnum = "PREMIUM" | "INTERIM_PROFESSIONAL" | "PROFESSIONAL" | "SPEAKER_ID" | "FINAL" | "MECHANICAL" | "CUSTOMER_APPROVED_RETURN" | "CUSTOMER_APPROVED_TRANSLATION" ;
