/**
 * Cielo24
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: devs@cielo24.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JobOptions } from './JobOptions';
import { HttpFile } from '../http/http';

export class JobInfoResponse {
    'jobId'?: string;
    'jobName'?: string;
    'mediaLengthSeconds'?: number;
    /**
    * Depends on third-party integrations.
    */
    'externalId'?: string;
    'priority'?: JobInfoResponsePriorityEnum;
    'fidelity'?: JobInfoResponseFidelityEnum;
    'jobStatus'?: JobInfoResponseJobStatusEnum;
    'options'?: JobOptions;
    'returnTargets'?: any;
    /**
    * RFC 5646 Language Code
    */
    'sourceLanguage'?: string;
    /**
    * RFC 5646 Language Code
    */
    'targetLanguage'?: string;
    /**
    * ISO 8601 Date String
    */
    'creationDate'?: string;
    /**
    * ISO 8601 Date String
    */
    'startDate'?: string;
    /**
    * ISO 8601 Date String
    */
    'dueDate'?: string;
    /**
    * ISO 8601 Date String
    */
    'completedDate'?: string;
    /**
    * ISO 8601 Date String
    */
    'returnDate'?: string;
    /**
    * ISO 8601 Date String
    */
    'authorizationDate'?: string;
    'jobDifficulty'?: JobInfoResponseJobDifficultyEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "jobId",
            "baseName": "JobId",
            "type": "string",
            "format": ""
        },
        {
            "name": "jobName",
            "baseName": "JobName",
            "type": "string",
            "format": ""
        },
        {
            "name": "mediaLengthSeconds",
            "baseName": "MediaLengthSeconds",
            "type": "number",
            "format": ""
        },
        {
            "name": "externalId",
            "baseName": "ExternalId",
            "type": "string",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "Priority",
            "type": "JobInfoResponsePriorityEnum",
            "format": ""
        },
        {
            "name": "fidelity",
            "baseName": "Fidelity",
            "type": "JobInfoResponseFidelityEnum",
            "format": ""
        },
        {
            "name": "jobStatus",
            "baseName": "JobStatus",
            "type": "JobInfoResponseJobStatusEnum",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "Options",
            "type": "JobOptions",
            "format": ""
        },
        {
            "name": "returnTargets",
            "baseName": "ReturnTargets",
            "type": "any",
            "format": ""
        },
        {
            "name": "sourceLanguage",
            "baseName": "SourceLanguage",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetLanguage",
            "baseName": "TargetLanguage",
            "type": "string",
            "format": ""
        },
        {
            "name": "creationDate",
            "baseName": "CreationDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "startDate",
            "baseName": "StartDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "dueDate",
            "baseName": "DueDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "completedDate",
            "baseName": "CompletedDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "returnDate",
            "baseName": "ReturnDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "authorizationDate",
            "baseName": "AuthorizationDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "jobDifficulty",
            "baseName": "JobDifficulty",
            "type": "JobInfoResponseJobDifficultyEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JobInfoResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export type JobInfoResponsePriorityEnum = "STANDARD" | "PRIORITY" ;
export type JobInfoResponseFidelityEnum = "MECHANICAL" | "PREMIUM" | "PROFESSIONAL" ;
export type JobInfoResponseJobStatusEnum = "Authorizing" | "Pending" | "In Process" | "Complete" | "Media Failure" | "Reviewing" ;
export type JobInfoResponseJobDifficultyEnum = "Good" | "Bad" | "Unknown" ;

