/**
 * Cielo24
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: devs@cielo24.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PerformTranscriptionBody {
    /**
    * The ID of the job
    */
    'jobId': string;
    /**
    * The desired fidelity of the transcription
    */
    'transcriptionFidelity': PerformTranscriptionBodyTranscriptionFidelityEnum;
    /**
    * The desired priority of the transcription
    */
    'priority': PerformTranscriptionBodyPriorityEnum;
    /**
    * A URL with query string which will be called on completion. If submitting the callback_url as a query string parameter, rather than a value in the POST data, the callback_url should be URL encoded. The callback URL can contain tags that will be replaced with job specific data when the callback is called. Below is the list of tags that are supported: {job_id}, {job_name}, {elementlist_version}, {iwp_name} (The Interim Work Product name associated with this ElementList version)
    */
    'callbackUrl'?: string;
    /**
    * A job options json. See JobOptions object for details.
    */
    'options'?: string;
    /**
    * An RFC 5646 language code to translate this job into. If not specified, then no translation will be performed. If specified, but the language code specified matches the language code on the job request, then no translation will be performed.
    */
    'targetLanguage'?: string;
    /**
    * The number of hours after submission that the job will be returned. If not specified, it will be set to a default based on the value of the priority parameter. The defaults are 24 and 48 for the PRIORITY and STANDARD priorities respectively. If you request a smaller number of hours than the default for the priority you have selected, the priority will be automatically changed. For example if you request a turnaround_hours of 16 with a priority of STANDARD, the priority will be automatically, and silently, changed to PRIORITY.
    */
    'turnaroundHours'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "jobId",
            "baseName": "job_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "transcriptionFidelity",
            "baseName": "transcription_fidelity",
            "type": "PerformTranscriptionBodyTranscriptionFidelityEnum",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "PerformTranscriptionBodyPriorityEnum",
            "format": ""
        },
        {
            "name": "callbackUrl",
            "baseName": "callback_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetLanguage",
            "baseName": "target_language",
            "type": "string",
            "format": ""
        },
        {
            "name": "turnaroundHours",
            "baseName": "turnaround_hours",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PerformTranscriptionBody.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PerformTranscriptionBodyTranscriptionFidelityEnum = "MECHANICAL" | "PREMIUM" | "PROFESSIONAL" ;
export type PerformTranscriptionBodyPriorityEnum = "STANDARD" | "PRIORITY" ;

